# Generated by Django 4.1.3 on 2022-12-15 19:22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "business_app",
            "0005_alter_business_bus_city_alter_business_bus_email_and_more",
        ),
        ("product_app", "0003_product_p_business_reltn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="p_business_reltn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="business_app.business",
                verbose_name="Seller",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="p_description",
            field=models.CharField(max_length=125, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="p_is_active",
            field=models.BooleanField(default=True, verbose_name="Available"),
        ),
        migrations.AlterField(
            model_name="product",
            name="p_name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Product Name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="p_price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=11,
                verbose_name="Price",
            ),
        ),
    ]
