# Generated by Django 4.1.3 on 2022-12-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0004_alter_product_p_business_reltn_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="p_is_active",
        ),
        migrations.AddField(
            model_name="product",
            name="p_instock",
            field=models.IntegerField(
                choices=[(1, "Available"), (2, "Out Of Stock")],
                default=1,
                verbose_name="Available",
            ),
            preserve_default=False,
        ),
    ]
