# Generated by Django 4.1.3 on 2022-12-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0005_remove_product_p_is_active_product_p_instock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="p_instock",
            field=models.IntegerField(
                choices=[(1, "Available"), (2, "Out Of Stock")],
                default=1,
                verbose_name="Available",
            ),
        ),
    ]
