# Generated by Django 4.1.3 on 2022-12-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="inv_paid_date",
            field=models.DateField(null=True),
        ),
    ]
