# Generated by Django 4.1.3 on 2022-12-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0003_alter_invoice_inv_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="inv_billed_date",
            field=models.DateField(null=True),
        ),
    ]
