# Generated by Django 4.1.3 on 2022-12-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_app", "0003_alter_business_bus_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_city",
            field=models.CharField(default="", max_length=50),
        ),
    ]
