# Generated by Django 4.1.3 on 2022-12-15 19:22

from django.db import migrations, models
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("business_app", "0004_alter_client_client_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="bus_city",
            field=models.CharField(default="", max_length=50, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="business",
            name="bus_email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="business",
            name="bus_name",
            field=models.CharField(max_length=75, verbose_name="Business Name"),
        ),
        migrations.AlterField(
            model_name="business",
            name="bus_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="bus_state",
            field=localflavor.us.models.USStateField(
                default="", max_length=2, verbose_name="State"
            ),
        ),
        migrations.AlterField(
            model_name="business",
            name="bus_street",
            field=models.CharField(max_length=50, verbose_name="Street"),
        ),
        migrations.AlterField(
            model_name="business",
            name="bus_zip",
            field=models.IntegerField(verbose_name="Zip"),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_name",
            field=models.CharField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_state",
            field=localflavor.us.models.USStateField(default="", max_length=2),
        ),
    ]
