# Generated by Django 4.1.3 on 2022-12-16 17:39

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ("business_app", "0006_alter_business_bus_state_alter_client_client_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="bus_state",
            field=localflavor.us.models.USStateField(max_length=2),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_state",
            field=localflavor.us.models.USStateField(max_length=2),
        ),
    ]
