# Generated by Django 4.1.3 on 2022-12-21 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("business_app", "0007_alter_business_bus_state_alter_client_client_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_bus_reltn",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="business_app.business",
            ),
            preserve_default=False,
        ),
    ]
