# Generated by Django 4.1.3 on 2022-12-21 20:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("business_app", "0008_client_client_bus_reltn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
    ]
