# Generated by Django 4.1.3 on 2023-02-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_app", "0009_alter_client_client_phone"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["client_name"], name="business_ap_client__141e3a_idx"
            ),
        ),
    ]
