# Generated by Django 4.1.3 on 2022-12-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="p_is_active",
            field=models.BooleanField(default=True),
        ),
    ]
