# Generated by Django 4.1.3 on 2022-12-17 22:29

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("payment_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="posted_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_amt",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=11,
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.IntegerField(
                choices=[(1, "Debit"), (2, "Credit")], verbose_name="Type"
            ),
        ),
    ]
