# Generated by Django 4.1.3 on 2022-12-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="bus_city",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AddField(
            model_name="business",
            name="bus_state",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="client_city",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AddField(
            model_name="client",
            name="client_state",
            field=models.CharField(default="", max_length=50),
        ),
    ]
