# Generated by Django 4.1.3 on 2022-12-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0005_lineitem_line_item_amt_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicefile",
            name="inv_slug",
            field=models.SlugField(
                default="", editable=False, max_length=275, unique=True
            ),
        ),
    ]
