# Generated by Django 4.1.3 on 2022-12-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0006_invoicefile_inv_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="inv_generated_date",
            field=models.DateTimeField(null=True),
        ),
    ]
