# Generated by Django 4.1.3 on 2022-12-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0007_invoice_inv_generated_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="inv_status",
            field=models.IntegerField(
                choices=[
                    (1, "Generated"),
                    (2, "Billed"),
                    (3, "Paid"),
                    (4, "Ready To Bill"),
                ]
            ),
        ),
    ]
