# Generated by Django 4.1.3 on 2022-12-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0008_alter_invoice_inv_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="inv_status",
            field=models.IntegerField(
                choices=[
                    (1, "Generated"),
                    (2, "Billed"),
                    (3, "Paid"),
                    (4, "Ready To Bill"),
                    (5, "Cancelled"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="line_item_qty",
            field=models.PositiveBigIntegerField(),
        ),
    ]
