# Generated by Django 4.1.3 on 2022-12-13 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0002_product_p_is_active"),
        ("invoice_app", "0010_alter_lineitem_line_item_qty_alter_lineitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="line_item_qty",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="product_app.product"
            ),
        ),
    ]
