# Generated by Django 4.1.3 on 2023-02-10 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0012_invoice_curr_amt_due_invoice_curr_amt_due_currency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoicefile",
            options={"managed": False},
        ),
    ]
