# Generated by Django 4.1.3 on 2023-02-14 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0013_alter_invoicefile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="line_item_qty",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
