# Generated by Django 4.1.3 on 2023-02-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0014_alter_lineitem_line_item_qty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineitem",
            name="line_item_qty",
            field=models.PositiveIntegerField(),
        ),
    ]
