# Generated by Django 4.1.3 on 2023-02-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0015_alter_lineitem_line_item_qty"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["inv_status"], name="invoice_app_inv_sta_6229ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["curr_amt_due"], name="invoice_app_curr_am_bd14f0_idx"
            ),
        ),
    ]
