# Generated by Django 4.1.3 on 2023-02-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_app", "0016_invoice_invoice_app_inv_sta_6229ab_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(
        'ALTER SEQUENCE invoice_app_invoice_id_seq RESTART WITH 1007;'
    )
    ]
